POST http://192.168.18.100:8000/api/login
Content-Type: application/json

{
  "username": "karom",
  "password": "password123"
}

###
GET http://192.168.18.100:8000/api/office
Content-Type: application/json
Authorization: Bearer 161|v5zXSnM1KMzWkvjRNykg69By0LZ7yH7Ee1nwmeAR5a33708d


###


POST http://192.168.18.100:8000/api/create-reservation
Content-Type: application/json
Authorization: Bearer 159|KtqzpiXeHpW9XikKxqZEAntPXJ5P7hprwXNxCcQS75a11507

{"branchId":"001","destinationService":"1","reason":"Keluhan","attendAtStart":"2023-10-18T07:00:02.224Z","attendAtEnd":"2023-10-18T08:00:02.224Z"}

  ###
### ===
POST http://192.168.18.100:8000/api/change-password
Content-Type: application/json
Authorization: Bearer 159|KtqzpiXeHpW9XikKxqZEAntPXJ5P7hprwXNxCcQS75a11507

{
    "old_password" : "password123",
    "new_password" : "12345678"
}